apiVersion: v1
kind: Service
metadata:
  name: srv-pod-1
spec:
  type: ClusterIP
  selector:
    app: pod-1-dns
  ports:
  - port: 8080
    targetPort: 80 # caso targetPort não seja declarado, por padrão ele será igual ao valor de port