apiVersion: v1
kind: Service
metadata:
  name: srv-pod-2
spec:
  type: NodePort
  selector:
    app: pod-2-dns
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000 # range 30000-32767
